Day08
thinkb4/a-walk-in-react pull request #6
Opened 2023-07-20 15:00 UTC by lichomonjelat

2023-07-20 15:27 UTC, maxikucan requested changes

2023-07-20 15:27 UTC, maxikucan commented on day_08.md
> +    export default function ProtectedRoute({ element }){
I think in this example the component should be named "PrivateRoute" to match with the previous example code.

2023-07-21 19:21 UTC, lichomonjelat commented on day_08.md
> +    export default function ProtectedRoute({ element }){
Thanks! just re-named the component

2023-07-21 19:24 UTC, maxikucan approved these changes

2023-07-21 19:25 UTC, merged